# Navigation Links
#   The weight parameter defines the order that the links will appear in.
# Stupid comment to be able to commit

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: about/
    weight: 20
  - name: Writing
    url: writing/
    weight: 30
  - name: Uses
    url: uses/
    weight: 40