baseURL = "https://lukasrobertson.org/"
languageCode = "en-us"
title = "Lukas Robertson"

[params]
  description = "Lukas Robertson — genetics and informatics student based in Barcelona."
  images = ["images/prof_profile.jpg"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
